"""European Commission Business and Consumer Surveys calendar connector (issue #24)."""

from .fetcher import (
    FetchRunSummary,
    ScheduleRunSummary,
    fetch_ec_bcs_calendar,
    schedule_ec_bcs_calendar,
)
from .indicators import (
    EC_BCS_BASE_URL,
    EC_BCS_PRESS_RELEASES_URL,
    EC_BCS_SURVEY_URL,
    INDICATOR_REGISTRY,
    EcBcsIndicatorSpec,
    reference_label_en,
)
from .parser import (
    EcBcsCalendarEventRecord,
    EcBcsCalendarRawRecord,
    EcBcsPressReleaseParseError,
    EcBcsValueObservation,
    parse_observation,
    parse_press_release_value,
)
from .projector import project_events, project_schedule_events, store_raw
from .schedule import (
    EC_BCS_RELEASE_TZ,
    EcBcsResolvedPressRelease,
    EcBcsScheduleDocument,
    EcBcsScheduleEntry,
    EcBcsScheduleParseError,
    discover_calendar_pdf_url,
    document_bytes_to_text,
    fetch_press_release_pdf,
    fetch_press_releases_listing_html,
    fetch_release_dates_document,
    fetch_survey_page_html,
    parse_release_dates_text,
    resolve_press_release_link,
    schedule_entry_to_records,
)

__all__ = [
    "EC_BCS_BASE_URL",
    "EC_BCS_PRESS_RELEASES_URL",
    "EC_BCS_RELEASE_TZ",
    "EC_BCS_SURVEY_URL",
    "EcBcsCalendarEventRecord",
    "EcBcsCalendarRawRecord",
    "EcBcsIndicatorSpec",
    "EcBcsPressReleaseParseError",
    "EcBcsResolvedPressRelease",
    "EcBcsScheduleDocument",
    "EcBcsScheduleEntry",
    "EcBcsScheduleParseError",
    "EcBcsValueObservation",
    "FetchRunSummary",
    "INDICATOR_REGISTRY",
    "ScheduleRunSummary",
    "discover_calendar_pdf_url",
    "document_bytes_to_text",
    "fetch_ec_bcs_calendar",
    "fetch_press_release_pdf",
    "fetch_press_releases_listing_html",
    "fetch_release_dates_document",
    "fetch_survey_page_html",
    "parse_observation",
    "parse_press_release_value",
    "parse_release_dates_text",
    "project_events",
    "project_schedule_events",
    "reference_label_en",
    "resolve_press_release_link",
    "schedule_ec_bcs_calendar",
    "schedule_entry_to_records",
    "store_raw",
]
