"""Cabinet Office / ESRI GDP connector (issue #14 P3a)."""

from __future__ import annotations

from .fetcher import (
    ALL_INDICATORS,
    FetchRunSummary,
    GdpValuesRunSummary,
    fetch_cao_gdp_calendar,
    fetch_cao_gdp_values,
)
from .indicators import (
    FIRST_PRELIMINARY,
    SECOND_PRELIMINARY,
    INDICATOR_REGISTRY,
    SPEC_BY_STAGE,
    CaoGdpIndicatorSpec,
)
from .parser import (
    CAO_GDP_ARCHIVE_INDEX_URL,
    CAO_GDP_ARCHIVE_YEAR_URL_TEMPLATE,
    CAO_GDP_RELEASE_TIME_LOCAL,
    CAO_GDP_RELEASE_TZ,
    CAO_GDP_REPORT_URL_TEMPLATE,
    CAO_GDP_SOURCE,
    PROVIDER,
    CaoGdpCalendarEventRecord,
    CaoGdpCalendarRawRecord,
    build_report_url,
)
from .projector import project_events, project_schedule_events, store_raw
from .reports import (
    CaoGdpReportParseError,
    CaoGdpValue,
    fetch_gdp_csv_text,
    fetch_gdp_report_menu_html,
    gdp_value_to_records,
    parse_gdp_growth_csv,
    parse_gdp_report_menu_html,
)
from .scraper import (
    CAO_GDP_BROWSER_HEADERS,
    CaoGdpArchiveParseError,
    CaoGdpReleaseEntry,
    archive_year_url,
    fetch_gdp_archive_index_html,
    fetch_gdp_archive_year_html,
    parse_gdp_archive_html,
    parse_gdp_archive_index_html,
    schedule_entry_to_records,
    select_archive_years,
)

__all__ = [
    "ALL_INDICATORS",
    "CAO_GDP_ARCHIVE_INDEX_URL",
    "CAO_GDP_ARCHIVE_YEAR_URL_TEMPLATE",
    "CAO_GDP_BROWSER_HEADERS",
    "CAO_GDP_RELEASE_TIME_LOCAL",
    "CAO_GDP_RELEASE_TZ",
    "CAO_GDP_REPORT_URL_TEMPLATE",
    "CAO_GDP_SOURCE",
    "CaoGdpArchiveParseError",
    "CaoGdpCalendarEventRecord",
    "CaoGdpCalendarRawRecord",
    "CaoGdpIndicatorSpec",
    "CaoGdpReleaseEntry",
    "CaoGdpReportParseError",
    "CaoGdpValue",
    "FetchRunSummary",
    "FIRST_PRELIMINARY",
    "GdpValuesRunSummary",
    "INDICATOR_REGISTRY",
    "PROVIDER",
    "SECOND_PRELIMINARY",
    "SPEC_BY_STAGE",
    "archive_year_url",
    "build_report_url",
    "fetch_cao_gdp_calendar",
    "fetch_cao_gdp_values",
    "fetch_gdp_archive_index_html",
    "fetch_gdp_archive_year_html",
    "fetch_gdp_csv_text",
    "fetch_gdp_report_menu_html",
    "gdp_value_to_records",
    "parse_gdp_archive_html",
    "parse_gdp_archive_index_html",
    "parse_gdp_growth_csv",
    "parse_gdp_report_menu_html",
    "project_events",
    "project_schedule_events",
    "schedule_entry_to_records",
    "select_archive_years",
    "store_raw",
]
