"""Site scrapers – calendar, news, indicators, and market data."""

from ._common import ScrapedIndicator, ScrapedMarketQuote, ScrapedNewsItem
from ingestion.sdmx._errors import (
    BISAPIError,
    BISRateLimitError,
    BundesbankAPIError,
    BundesbankRateLimitError,
    ECBAPIError,
    ECBRateLimitError,
    EurostatAPIError,
    EurostatRateLimitError,
    ILOAPIError,
    ILORateLimitError,
    UNSDAPIError,
    UNSDRateLimitError,
)
from ingestion.sdmx._types import (
    SDMXDataStructure as ECBDataStructure,
    SDMXDataStructure as EurostatDataStructure,
    SDMXDataStructure as ILODataStructure,
    SDMXDataStructure as UNSDDataStructure,
    SDMXDataflow as ECBDataflow,
    SDMXDataflow as EurostatDataflow,
    SDMXDataflow as ILODataflow,
    SDMXDataflow as UNSDDataflow,
    SDMXDimension as ECBDimension,
    SDMXDimension as EurostatDimension,
    SDMXDimension as ILODimension,
    SDMXDimension as UNSDDimension,
    SDMXObservation as BISObservation,
    SDMXObservation as BundesbankObservation,
    SDMXObservation as ECBObservation,
    SDMXObservation as EurostatObservation,
    SDMXObservation as ILOObservation,
    SDMXObservation as UNSDObservation,
    SDMXSizeEstimate as ECBSizeEstimate,
    SDMXSizeEstimate as EurostatSizeEstimate,
    SDMXSizeEstimate as ILOSizeEstimate,
    SDMXSizeEstimate as UNSDSizeEstimate,
    SDMXStructureSummary as ECBStructureSummary,
    SDMXStructureSummary as EurostatStructureSummary,
    SDMXStructureSummary as ILOStructureSummary,
    SDMXStructureSummary as UNSDStructureSummary,
)
from ingestion.sdmx.providers.bis import BISClient
from ingestion.sdmx.providers.bundesbank import BundesbankClient
from ingestion.sdmx.providers.ecb import ECBClient
from ingestion.sdmx.providers.eurostat import EurostatClient
from ingestion.sdmx.providers.ilo import ILOClient
from ingestion.sdmx.providers.unsd import UNSDClient
from .bea import (
    BEAAPIError,
    BEAClient,
    BEADataset,
    BEAObservation,
    BEAParameter,
    BEAParameterValue,
    BEARateLimitError,
    BEAResponseError,
)
from .census import (
    CensusAPIError,
    CensusClient,
    CensusDataset,
    CensusGeography,
    CensusObservation,
    CensusRateLimitError,
    CensusResponseError,
    CensusVariable,
)
from .bls import (
    BLSAPIError,
    BLSClient,
    BLSObservation,
    BLSRateLimitError,
    BLSResponseError,
    BLSSeriesInfo,
    BLSSurvey,
)
from .eia import (
    EIAAPIError,
    EIAClient,
    EIAFacet,
    EIAObservation,
    EIARateLimitError,
    EIAResponseError,
    EIARoute,
)
from .forexfactory import ForexFactoryCalendarClient, ForexFactoryNewsClient
from .fred import (
    FredAPIError,
    FredClient,
    FredObservation,
    FredRateLimitError,
    FredVintageObservation,
)
from ingestion.sdmx._errors import IMFAPIError, IMFRateLimitError
from ingestion.sdmx._types import SDMXObservation as IMFObservation
from ingestion.sdmx.providers.imf import IMFClient, IMFVintageObservation
from .investing import InvestingCalendarClient, InvestingNewsClient
from ingestion.sdmx._errors import OECDAPIError, OECDRateLimitError, OECDResponseFormatError
from ingestion.sdmx.providers.oecd import (
    OECDClient,
    OECDCode,
    OECDDataStructure,
    OECDDataflow,
    OECDDimension,
    OECDObservation,
    OECDSeries,
    OECDStructureSummary,
)
from .bloomberg import BloombergArticle, BloombergArticleClient, BloombergNewsClient
from .ft import FTArticle, FTArticleClient, FTNewsClient
from .reuters import ReutersArticle, ReutersArticleClient, ReutersNewsClient
from .treasury_fiscal import TreasuryFiscalClient, TreasuryFiscalObservation
from .worldbank import (
    WorldBankAPIError,
    WorldBankClient,
    WorldBankCountry,
    WorldBankIndicatorInfo,
    WorldBankObservation,
    WorldBankRateLimitError,
    WorldBankResponseFormatError,
    WorldBankSource,
    WorldBankTopic,
)
from .aisi import (
    AISIClient,
    AISIObservation,
    AISIWeeklySteelReport,
    parse_weekly_raw_steel_page,
)
from .ism import (
    ISMClient,
    ISMObservation,
    ISMReport,
    ISMReportMetric,
    ISMReportParseError,
    discover_current_report_urls,
    parse_ism_report_page,
)
from .redbook import (
    RedbookAPIError,
    RedbookAuthError,
    RedbookClient,
    RedbookHistoricalRow,
    RedbookObservation,
    parse_redbook_historical_rows,
)
from .sentix import (
    SENTIX_API_BASE_URL,
    SENTIX_AUTH_PATH,
    SENTIX_HOMEPAGE_URL,
    SENTIX_TIMESERIES_PATH,
    SentixAPIError,
    SentixAuthError,
    SentixClient,
    SentixObservation,
    SentixSeriesRow,
    parse_sentix_timeseries,
)
from .wsj import WSJArticle, WSJArticleClient, WSJNewsClient
from .gov_report import GovReportClient, GovReportItem
from .mof_jgb import MOFJGBClient, MOFJGBObservation, parse_jgb_interest_rate_csv
from .nyfed import NYFedGSCPI, NYFedRate, NYFedRatesClient
from .rateprobability import (
    FedMeetingProbability,
    FedRateProbability,
    RateProbabilityClient,
)
from .reddit import RedditTrendClient, RedditTrendPost
from .tradingeconomics import (
    TradingEconomicsCalendarClient,
    TradingEconomicsIndicatorsClient,
    TradingEconomicsMarketsClient,
    TradingEconomicsNewsClient,
)
from .weibo import WeiboTrendClient, WeiboTrendItem

__all__ = [
    # Data classes
    "AISIObservation",
    "AISIWeeklySteelReport",
    "BEAAPIError",
    "BEADataset",
    "BEAObservation",
    "BEAParameter",
    "BEAParameterValue",
    "BEARateLimitError",
    "BEAResponseError",
    "CensusAPIError",
    "CensusDataset",
    "CensusGeography",
    "CensusObservation",
    "CensusRateLimitError",
    "CensusResponseError",
    "CensusVariable",
    "BLSAPIError",
    "BLSObservation",
    "BLSRateLimitError",
    "BLSResponseError",
    "BLSSeriesInfo",
    "BLSSurvey",
    "BISObservation",
    "BloombergArticle",
    "BundesbankAPIError",
    "BundesbankObservation",
    "BundesbankRateLimitError",
    "ECBAPIError",
    "ECBDataStructure",
    "ECBDataflow",
    "ECBDimension",
    "ECBObservation",
    "ECBRateLimitError",
    "ECBSizeEstimate",
    "ECBStructureSummary",
    "EIAAPIError",
    "EIAFacet",
    "EIAObservation",
    "EIARateLimitError",
    "EIAResponseError",
    "EIARoute",
    "EurostatAPIError",
    "EurostatDataStructure",
    "EurostatDataflow",
    "EurostatDimension",
    "EurostatObservation",
    "EurostatRateLimitError",
    "EurostatSizeEstimate",
    "EurostatStructureSummary",
    "FTArticle",
    "ILOAPIError",
    "ILODataStructure",
    "ILODataflow",
    "ILODimension",
    "ILOObservation",
    "ILORateLimitError",
    "ILOSizeEstimate",
    "ILOStructureSummary",
    "ISMObservation",
    "ISMReport",
    "ISMReportMetric",
    "ISMReportParseError",
    "FedMeetingProbability",
    "FedRateProbability",
    "FredAPIError",
    "FredObservation",
    "FredRateLimitError",
    "FredVintageObservation",
    "GovReportClient",
    "GovReportItem",
    "IMFAPIError",
    "IMFObservation",
    "IMFRateLimitError",
    "IMFVintageObservation",
    "MOFJGBObservation",
    "NYFedGSCPI",
    "NYFedRate",
    "OECDAPIError",
    "OECDCode",
    "OECDDataStructure",
    "OECDDataflow",
    "OECDDimension",
    "OECDObservation",
    "OECDRateLimitError",
    "OECDResponseFormatError",
    "OECDSeries",
    "OECDStructureSummary",
    "ReutersArticle",
    "RedbookAPIError",
    "RedbookAuthError",
    "RedbookHistoricalRow",
    "RedbookObservation",
    "SentixAPIError",
    "SentixAuthError",
    "SentixObservation",
    "SentixSeriesRow",
    "RedditTrendPost",
    "ScrapedIndicator",
    "ScrapedMarketQuote",
    "ScrapedNewsItem",
    "TreasuryFiscalObservation",
    "UNSDAPIError",
    "UNSDDataStructure",
    "UNSDDataflow",
    "UNSDDimension",
    "UNSDObservation",
    "UNSDRateLimitError",
    "UNSDSizeEstimate",
    "UNSDStructureSummary",
    "WSJArticle",
    "WorldBankAPIError",
    "WorldBankCountry",
    "WorldBankIndicatorInfo",
    "WorldBankObservation",
    "WorldBankRateLimitError",
    "WorldBankResponseFormatError",
    "WorldBankSource",
    "WorldBankTopic",
    # Calendar
    "ForexFactoryCalendarClient",
    "InvestingCalendarClient",
    "TradingEconomicsCalendarClient",
    # News
    "BloombergNewsClient",
    "FTNewsClient",
    "ForexFactoryNewsClient",
    "InvestingNewsClient",
    "ReutersNewsClient",
    "TradingEconomicsNewsClient",
    "WSJNewsClient",
    # Articles
    "BloombergArticleClient",
    "FTArticleClient",
    "ReutersArticleClient",
    "RedditTrendClient",
    "WeiboTrendClient",
    "WeiboTrendItem",
    "WSJArticleClient",
    # Structured Data APIs
    "AISIClient",
    "BEAClient",
    "CensusClient",
    "BLSClient",
    "BISClient",
    "BundesbankClient",
    "ECBClient",
    "EIAClient",
    "EurostatClient",
    "FredClient",
    "ILOClient",
    "IMFClient",
    "ISMClient",
    "MOFJGBClient",
    "OECDClient",
    "RedbookClient",
    "SentixClient",
    "TreasuryFiscalClient",
    "UNSDClient",
    "WorldBankClient",
    # Indicators & Markets
    "TradingEconomicsIndicatorsClient",
    "TradingEconomicsMarketsClient",
    # Rate Probabilities & Reference Rates
    "NYFedRatesClient",
    "RateProbabilityClient",
    "discover_current_report_urls",
    "parse_ism_report_page",
    "parse_redbook_historical_rows",
    "parse_sentix_timeseries",
    "SENTIX_API_BASE_URL",
    "SENTIX_AUTH_PATH",
    "SENTIX_HOMEPAGE_URL",
    "SENTIX_TIMESERIES_PATH",
    "parse_weekly_raw_steel_page",
    "parse_jgb_interest_rate_csv",
]
