"""Site scrapers – calendar, news, indicators, and market data."""

from ._common import ScrapedIndicator, ScrapedMarketQuote, ScrapedNewsItem
from ingestion.sdmx._errors import (
    BISAPIError,
    BISRateLimitError,
    ECBAPIError,
    ECBRateLimitError,
    EurostatAPIError,
    EurostatRateLimitError,
    ILOAPIError,
    ILORateLimitError,
    UNSDAPIError,
    UNSDRateLimitError,
)
from ingestion.sdmx._types import (
    SDMXDataStructure as ECBDataStructure,
    SDMXDataStructure as EurostatDataStructure,
    SDMXDataStructure as ILODataStructure,
    SDMXDataStructure as UNSDDataStructure,
    SDMXDataflow as ECBDataflow,
    SDMXDataflow as EurostatDataflow,
    SDMXDataflow as ILODataflow,
    SDMXDataflow as UNSDDataflow,
    SDMXDimension as ECBDimension,
    SDMXDimension as EurostatDimension,
    SDMXDimension as ILODimension,
    SDMXDimension as UNSDDimension,
    SDMXObservation as BISObservation,
    SDMXObservation as ECBObservation,
    SDMXObservation as EurostatObservation,
    SDMXObservation as ILOObservation,
    SDMXObservation as UNSDObservation,
    SDMXSizeEstimate as ECBSizeEstimate,
    SDMXSizeEstimate as EurostatSizeEstimate,
    SDMXSizeEstimate as ILOSizeEstimate,
    SDMXSizeEstimate as UNSDSizeEstimate,
    SDMXStructureSummary as ECBStructureSummary,
    SDMXStructureSummary as EurostatStructureSummary,
    SDMXStructureSummary as ILOStructureSummary,
    SDMXStructureSummary as UNSDStructureSummary,
)
from ingestion.sdmx.providers.bis import BISClient
from ingestion.sdmx.providers.ecb import ECBClient
from ingestion.sdmx.providers.eurostat import EurostatClient
from ingestion.sdmx.providers.ilo import ILOClient
from ingestion.sdmx.providers.unsd import UNSDClient
from .bea import (
    BEAAPIError,
    BEAClient,
    BEADataset,
    BEAObservation,
    BEAParameter,
    BEAParameterValue,
    BEARateLimitError,
    BEAResponseError,
)
from .census import (
    CensusAPIError,
    CensusClient,
    CensusDataset,
    CensusGeography,
    CensusObservation,
    CensusRateLimitError,
    CensusResponseError,
    CensusVariable,
)
from .bls import (
    BLSAPIError,
    BLSClient,
    BLSObservation,
    BLSRateLimitError,
    BLSResponseError,
    BLSSeriesInfo,
    BLSSurvey,
)
from .eia import EIAClient, EIAObservation
from .forexfactory import ForexFactoryCalendarClient, ForexFactoryNewsClient
from .fred import (
    FredAPIError,
    FredClient,
    FredObservation,
    FredRateLimitError,
    FredVintageObservation,
)
from .imf import IMFClient, IMFObservation, IMFVintageObservation
from .investing import InvestingCalendarClient, InvestingNewsClient
from .oecd import (
    OECDAPIError,
    OECDClient,
    OECDCode,
    OECDDataStructure,
    OECDDataflow,
    OECDDimension,
    OECDObservation,
    OECDRateLimitError,
    OECDResponseFormatError,
    OECDSeries,
    OECDStructureSummary,
)
from .bloomberg import BloombergArticle, BloombergArticleClient, BloombergNewsClient
from .ft import FTArticle, FTArticleClient, FTNewsClient
from .reuters import ReutersArticle, ReutersArticleClient, ReutersNewsClient
from .treasury_fiscal import TreasuryFiscalClient, TreasuryFiscalObservation
from .worldbank import (
    WorldBankAPIError,
    WorldBankClient,
    WorldBankCountry,
    WorldBankIndicatorInfo,
    WorldBankObservation,
    WorldBankRateLimitError,
    WorldBankResponseFormatError,
    WorldBankSource,
    WorldBankTopic,
)
from .wsj import WSJArticle, WSJArticleClient, WSJNewsClient
from .gov_report import GovReportClient, GovReportItem
from .nyfed import NYFedRate, NYFedRatesClient
from .rateprobability import (
    FedMeetingProbability,
    FedRateProbability,
    RateProbabilityClient,
)
from .reddit import RedditTrendClient, RedditTrendPost
from .tradingeconomics import (
    TradingEconomicsCalendarClient,
    TradingEconomicsIndicatorsClient,
    TradingEconomicsMarketsClient,
    TradingEconomicsNewsClient,
)
from .weibo import WeiboTrendClient, WeiboTrendItem

__all__ = [
    # Data classes
    "BEAAPIError",
    "BEADataset",
    "BEAObservation",
    "BEAParameter",
    "BEAParameterValue",
    "BEARateLimitError",
    "BEAResponseError",
    "CensusAPIError",
    "CensusDataset",
    "CensusGeography",
    "CensusObservation",
    "CensusRateLimitError",
    "CensusResponseError",
    "CensusVariable",
    "BLSAPIError",
    "BLSObservation",
    "BLSRateLimitError",
    "BLSResponseError",
    "BLSSeriesInfo",
    "BLSSurvey",
    "BISObservation",
    "BloombergArticle",
    "ECBAPIError",
    "ECBDataStructure",
    "ECBDataflow",
    "ECBDimension",
    "ECBObservation",
    "ECBRateLimitError",
    "ECBSizeEstimate",
    "ECBStructureSummary",
    "EIAObservation",
    "EurostatAPIError",
    "EurostatDataStructure",
    "EurostatDataflow",
    "EurostatDimension",
    "EurostatObservation",
    "EurostatRateLimitError",
    "EurostatSizeEstimate",
    "EurostatStructureSummary",
    "FTArticle",
    "ILOAPIError",
    "ILODataStructure",
    "ILODataflow",
    "ILODimension",
    "ILOObservation",
    "ILORateLimitError",
    "ILOSizeEstimate",
    "ILOStructureSummary",
    "FedMeetingProbability",
    "FedRateProbability",
    "FredAPIError",
    "FredObservation",
    "FredRateLimitError",
    "FredVintageObservation",
    "GovReportClient",
    "GovReportItem",
    "IMFObservation",
    "IMFVintageObservation",
    "NYFedRate",
    "OECDAPIError",
    "OECDCode",
    "OECDDataStructure",
    "OECDDataflow",
    "OECDDimension",
    "OECDObservation",
    "OECDRateLimitError",
    "OECDResponseFormatError",
    "OECDSeries",
    "OECDStructureSummary",
    "ReutersArticle",
    "RedditTrendPost",
    "ScrapedIndicator",
    "ScrapedMarketQuote",
    "ScrapedNewsItem",
    "TreasuryFiscalObservation",
    "UNSDAPIError",
    "UNSDDataStructure",
    "UNSDDataflow",
    "UNSDDimension",
    "UNSDObservation",
    "UNSDRateLimitError",
    "UNSDSizeEstimate",
    "UNSDStructureSummary",
    "WSJArticle",
    "WorldBankAPIError",
    "WorldBankCountry",
    "WorldBankIndicatorInfo",
    "WorldBankObservation",
    "WorldBankRateLimitError",
    "WorldBankResponseFormatError",
    "WorldBankSource",
    "WorldBankTopic",
    # Calendar
    "ForexFactoryCalendarClient",
    "InvestingCalendarClient",
    "TradingEconomicsCalendarClient",
    # News
    "BloombergNewsClient",
    "FTNewsClient",
    "ForexFactoryNewsClient",
    "InvestingNewsClient",
    "ReutersNewsClient",
    "TradingEconomicsNewsClient",
    "WSJNewsClient",
    # Articles
    "BloombergArticleClient",
    "FTArticleClient",
    "ReutersArticleClient",
    "RedditTrendClient",
    "WeiboTrendClient",
    "WeiboTrendItem",
    "WSJArticleClient",
    # Structured Data APIs
    "BEAClient",
    "CensusClient",
    "BLSClient",
    "BISClient",
    "ECBClient",
    "EIAClient",
    "EurostatClient",
    "FredClient",
    "ILOClient",
    "IMFClient",
    "OECDClient",
    "TreasuryFiscalClient",
    "UNSDClient",
    "WorldBankClient",
    # Indicators & Markets
    "TradingEconomicsIndicatorsClient",
    "TradingEconomicsMarketsClient",
    # Rate Probabilities & Reference Rates
    "NYFedRatesClient",
    "RateProbabilityClient",
]
