#!/usr/bin/env python3
"""Generate ``docs/ops_index.md`` from the ``_op_*`` methods in
``src/macro_data/service/``.

Pure AST walk — no project import — so it runs anywhere with vanilla
Python 3.11+. Output is deterministic (ops sorted within each mixin).

Run::

    python3 tools/gen_ops_index.py

Wire into pre-commit / CI to keep the index current — the tool exits
non-zero only on parse failure, so a stale index will not block a
commit on its own. The recommended CI step is ``git diff --exit-code
docs/ops_index.md`` after running the generator.
"""

from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVICE_DIR = ROOT / "src" / "macro_data" / "service"
OUTPUT = ROOT / "docs" / "ops_index.md"

# (Section title, mixin filename) — order drives display order in the
# generated doc. Mirrors the composition in
# ``src/macro_data/service/__init__.py``.
MIXIN_FILES: list[tuple[str, str]] = [
    ("Calendar", "_calendar.py"),
    ("Timeseries", "_timeseries.py"),
    ("Documents", "_documents.py"),
    ("News", "_news.py"),
    ("Market", "_market.py"),
    ("Health / Refresh", "_ops_health.py"),
]


def _first_paragraph(doc: str) -> str:
    """Collapse the docstring's first non-blank paragraph onto one line.

    A paragraph ends at the first blank line; physical line wraps inside
    it become single spaces so wrapped sentences render whole.
    """
    lines: list[str] = []
    for raw in doc.splitlines():
        stripped = raw.strip()
        if not stripped:
            if lines:
                break
            continue
        lines.append(stripped)
    return " ".join(lines) if lines else "(no docstring)"


def extract_ops(path: Path) -> list[tuple[str, str]]:
    """Return ``[(op_name, summary)]`` for every ``_op_*`` method in *path*.

    Walks every class body in the module so a future split that puts
    ops on a helper class still picks them up. Summary is the first
    paragraph of the method's docstring (line wraps collapsed), or a
    placeholder.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    out: list[tuple[str, str]] = []
    for cls in (n for n in tree.body if isinstance(n, ast.ClassDef)):
        for fn in cls.body:
            if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if not fn.name.startswith("_op_"):
                continue
            op = fn.name[len("_op_"):]
            doc = ast.get_docstring(fn) or ""
            out.append((op, _first_paragraph(doc)))
    out.sort()
    return out


def _escape_cell(text: str) -> str:
    return text.replace("|", "\\|")


def render() -> str:
    sections: list[tuple[str, str, list[tuple[str, str]]]] = []
    for label, filename in MIXIN_FILES:
        ops = extract_ops(SERVICE_DIR / filename)
        sections.append((label, filename, ops))
    grand_total = sum(len(ops) for _, _, ops in sections)

    lines = [
        "# Service Operation Index",
        "",
        "Auto-generated by `tools/gen_ops_index.py`. Do not edit by hand.",
        "",
        "Lists every `_op_<name>` method exposed by `LocalMacroDataService`,",
        "grouped by mixin. The op name is the value passed to",
        "`service.invoke(operation_name, arguments)`; the summary is the",
        "first line of the method's docstring.",
        "",
        f"Total: **{grand_total}** ops across {len(MIXIN_FILES)} mixins.",
        "",
    ]
    for label, filename, ops in sections:
        lines.append(f"## {label} (`{filename}`) — {len(ops)} ops")
        lines.append("")
        lines.append("| Op | Summary |")
        lines.append("| --- | --- |")
        for op, summary in ops:
            lines.append(f"| `{op}` | {_escape_cell(summary)} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
